### ISSUE TITLE
Feedback for code

### ISSUE THREAD

**Issue by Anandhi-R** [nicluigisciarra/VU#2]
When you run the script without creating any file and select option 2, the script asks you to enter website name, username and the password. After that, it throws an error message - "FileNotFoundError". You must check if the file exists before asking for the details. Please fix this issue.

Also, when you run the script for the first time and select option 3, it asks me "Would you like to add an account? (yes/no)" - when I type "no", I am getting an "Invalid input" msg, which is confusing!

When the option 1 is selected, and input the user details, I am getting an error msg (FileNotFoundError) saying that the file 'webaccountdata.txt' does not exist. Proper validation must be done. Unable to check the script further.

**Comment by nicluigisciarra** [comment]
I understand, I have been doing all the debugging and work in the MAIN_WITH_LOGIN_PORTAL and so everything in the MAIN file is outdated compared to the other. I may just keep the single MAIN_WITH_LOGIN_PORTAL and delete the others to prevent confusion.

**Comment by Anandhi-R** [comment]
The script fulfills all the assessment requirements and offers additional options and validations, ensuring users can securely store and retrieve information. You can proceed with submitting this file. Good work.

However, I've observed a minor issue that need not be implemented: 

1. When users search for an account using the website name, the script appears to search for matches with the first character capitalised. For instance, "[www.gmail.com](http://www.gmail.com/)" might not be retrieved because the script is searching for "[Www.gmail.com](http://www.gmail.com/)".
